version: '3.7'

services:

        db:
                container_name: postgres13-001
                image: postgres:13-alpine
                restart: always
                #env_file: common.env
                environment:
                       POSTGRES_PASSWORD: 123456
                       POSTGRES_DB: postgres
                       POSTGRES_USER: postgres
                volumes:
                      - "vol1:/var/lib/postgresql/data"
                ports:
                   - "5450:5432"


        pgadmin:
                container_name: pgadmin4-001
                image: dpage/pgadmin4:latest
                restart: always
                environment:
                   PGADMIN_DEFAULT_EMAIL: alvarezrobert150@gmail.com
                   PGADMIN_DEFAULT_PASSWORD: 123456
                   PGADMIN_LISTEN_PORT: 80
                ports:
                   - "5050:80"
                volumes:
                   - pgadmin-data:/var/lib/pgadmin
                links:
                   - "db:pgsql-server"
volumes:
        vol1:
        pgadmin-data:
